### ISSUE TITLE
Unable to save sample set

### ISSUE THREAD

**Issue by jordur** [saowwapark/inCNV#3]
Dear Saowwapark Chanwigoon, 
I have been able to install and configure inCNV. Moreover, I have edited the cn.mops csv results to a .tsv file with required fields. However, I am not able to save a sample set. Once added the sample names as the "sample names" field, I tried to ADD the sample set to the repository. However nothing occurs (nor logs) and the sample set doesn't appear and the sample set database seems to be empty. Should I change some db parameters in order to be able to write the database?
Attached you will find the docker-compose.yml.zip file
Thank you very much in advanc
[docker-compose.zip](https://github.com/saowwapark/inCNV/files/7882005/docker-compose.zip)

**Comment by amendal** [comment]
I have the same problem here! Have you fix it??

**Comment by jordur** [comment]
Not yet! In fact I have reinstalled the docker machine and I suspect a problem with some databases.
Any advice will be really appreciated!
Regards,

**Comment by saowwapark** [comment]
I apologize for this regression issue. I've already fixed it.

To be honest, This happened because my incorrect pipeline immediately build images when I push codes to test.

**Comment by saowwapark** [comment]
I apologize for this regression issue. I've already fixed it.

To be honest, This happened because my incorrect pipeline immediately build images when I push codes to test.
